from django.db import models

class flocculation_data(models.Model):
    surface_water = models.CharField(max_length=50, blank=False, default='')
    initial_pH = models.FloatField(blank=False, default='')
    initial_EC = models.IntegerField(blank=False, default='')
    initial_turbidity = models.IntegerField(blank=False, default='')
    flocculant = models.CharField(max_length=50, blank=False, default='')
    floc_dose = models.IntegerField(blank=False, default='')
    floc_concentration = models.FloatField(blank=False, default='')
    floc_saline_Molarity = models.FloatField(blank=False, default='')
    floc_cactus_share = models.FloatField(blank=False, default='')
    floc_vol = models.FloatField(blank=False, default='')
    saline_concentration = models.FloatField(blank=False, default='')
    final_pH = models.FloatField(blank=False, default='')
    final_EC = models.IntegerField(blank=False, default='')
    final_turbidity = models.IntegerField(blank=False, default='')
    cal_final_EC = models.FloatField(blank=False, default='')
    delta_EC = models.FloatField(blank=False, default='')
    stirring_speed_coagulation_phase = models.IntegerField(blank=False, default='')
    duration_coagulation_phase = models.IntegerField(blank=False, default='')
    stirring_speed_flocculation_phase = models.IntegerField(blank=False, default='')
    duration_flocculation_phase = models.IntegerField(blank=False, default='')
    duration_sedimentation_phase = models.IntegerField(blank=False, default='')

class bsf_data(models.Model):
    diameter = models.IntegerField(blank=False, default='')
    material = models.CharField(max_length=50, blank=False, default='')
    material_height = models.FloatField(blank=False, default='')
    min_grain_diameter = models.FloatField(blank=False, default='')
    max_grain_diameter = models.FloatField(blank=False, default='')
    mean_grain_diameter = models.FloatField(blank=False, default='')
    min_flow = models.FloatField(blank=False, default='')
    max_flow = models.FloatField(blank=False, default='')
    mean_flow = models.FloatField(blank=False, default='')
    min_pause = models.IntegerField(blank=False, default='')
    max_pause = models.IntegerField(blank=False, default='')
    mean_pause = models.IntegerField(blank=False, default='')
    time_schmutzdecke = models.IntegerField(blank=False, default='')
    initial_ecoli = models.FloatField(blank=False, default='')
    final_ecoli = models.FloatField(blank=False, default='')
    initial_turbidity = models.IntegerField(blank=False, default='')
    final_turbidity = models.IntegerField(blank=False, default='')

class aaa_data(models.Model):
    c = models.FloatField(blank=False, default="")
    t = models.FloatField(blank=False, default="")
    q = models.FloatField(blank=False, default="")
