# Generated by Django 4.1.3 on 2023-02-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='optimizeTurData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_assessment', models.BooleanField(default=False)),
                ('load_pipe', models.BooleanField(default=False)),
                ('pred_type', models.CharField(choices=[('ec', 'ec'), ('ph', 'ph'), ('tur', 'tur')], max_length=3)),
                ('surface_water', models.CharField(choices=[('model suspension', 'model suspension'), ('Rhein', 'Rhein'), ('Main', 'Main'), ('Mühlbach', 'Mühlbach')], max_length=50)),
                ('initial_pH_min', models.FloatField(default='8.5')),
                ('initial_pH_max', models.FloatField(default='8.5')),
                ('initial_EC_min', models.IntegerField(default='400')),
                ('initial_EC_max', models.IntegerField(default='400')),
                ('initial_turbidity_min', models.IntegerField(default='135')),
                ('initial_turbidity_max', models.IntegerField(default='135')),
                ('flocculant', models.CharField(choices=[('Moringa', 'Moringa'), ('Kaktus', 'Kaktus'), ('MoringaKaktus', 'MoringaKaktus')], max_length=50)),
                ('floc_concentration_min', models.IntegerField(default='20')),
                ('floc_concentration_max', models.IntegerField(default='20')),
                ('floc_saline_Molarity_min', models.FloatField(default='0.3')),
                ('floc_saline_Molarity_max', models.FloatField(default='0.3')),
                ('floc_dose_min', models.IntegerField(default='200')),
                ('floc_dose_max', models.IntegerField(default='200')),
                ('floc_cactus_share_min', models.IntegerField(default='0')),
                ('floc_cactus_share_max', models.IntegerField(default='0')),
                ('stirring_speed_coagulation_phase_min', models.IntegerField(default='100')),
                ('stirring_speed_coagulation_phase_max', models.IntegerField(default='100')),
                ('duration_coagulation_phase_min', models.IntegerField(default='1')),
                ('duration_coagulation_phase_max', models.IntegerField(default='1')),
                ('stirring_speed_flocculation_phase_min', models.IntegerField(default='20')),
                ('stirring_speed_flocculation_phase_max', models.IntegerField(default='20')),
                ('duration_flocculation_phase_min', models.IntegerField(default='15')),
                ('duration_flocculation_phase_max', models.IntegerField(default='15')),
                ('duration_sedimentation_phase_min', models.IntegerField(default='45')),
                ('duration_sedimentation_phase_max', models.IntegerField(default='45')),
            ],
        ),
        migrations.CreateModel(
            name='predictECData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_assessment', models.BooleanField(default=False)),
                ('load_pipe', models.BooleanField(default=False)),
                ('initial_EC', models.IntegerField(default='400')),
                ('floc_concentration', models.FloatField(default='20')),
                ('floc_saline_Molarity', models.FloatField(default='0.3')),
                ('floc_dose', models.IntegerField(default='200')),
            ],
        ),
        migrations.CreateModel(
            name='predictpHData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_assessment', models.BooleanField(default=False)),
                ('load_pipe', models.BooleanField(default=False)),
                ('initial_pH', models.FloatField(default='8.5')),
                ('floc_concentration', models.FloatField(default='20')),
                ('floc_saline_Molarity', models.FloatField(default='0.3')),
                ('floc_dose', models.IntegerField(default='200')),
            ],
        ),
        migrations.CreateModel(
            name='predictTurData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_assessment', models.BooleanField(default=False)),
                ('load_pipe', models.BooleanField(default=False)),
                ('surface_water', models.CharField(choices=[('model suspension', 'model suspension'), ('Rhein', 'Rhein'), ('Main', 'Main'), ('Mühlbach', 'Mühlbach')], max_length=50)),
                ('initial_pH', models.FloatField(default='8.5')),
                ('initial_EC', models.IntegerField(default='400')),
                ('initial_turbidity', models.IntegerField(default='135')),
                ('flocculant', models.CharField(choices=[('Moringa', 'Moringa'), ('Kaktus', 'Kaktus'), ('MoringaKaktus', 'MoringaKaktus')], max_length=50)),
                ('floc_saline_Molarity', models.FloatField(default='0.3')),
                ('floc_dose', models.IntegerField(default='200')),
                ('floc_cactus_share', models.IntegerField(default='0')),
                ('stirring_speed_coagulation_phase', models.IntegerField(default='100')),
                ('duration_coagulation_phase', models.IntegerField(default='1')),
                ('stirring_speed_flocculation_phase', models.IntegerField(default='20')),
                ('duration_flocculation_phase', models.IntegerField(default='15')),
                ('duration_sedimentation_phase', models.IntegerField(default='45')),
            ],
        ),
    ]
