# Generated by Django 4.1.3 on 2022-11-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flocculation_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_water', models.CharField(default='', max_length=50)),
                ('initial_pH', models.CharField(default='', max_length=50)),
                ('initial_EC', models.CharField(default='', max_length=50)),
                ('initial_turbidity', models.CharField(default='', max_length=50)),
                ('flocculant', models.CharField(default='', max_length=50)),
                ('floc_dose', models.CharField(default='', max_length=50)),
                ('concentration', models.CharField(default='', max_length=50)),
                ('saline_Molarity', models.CharField(default='', max_length=50)),
                ('cactus_share', models.CharField(default='', max_length=50)),
                ('floc_vol', models.CharField(default='', max_length=50)),
                ('saline_concentration', models.CharField(default='', max_length=50)),
                ('final_pH', models.CharField(default='', max_length=50)),
                ('final_EC', models.CharField(default='', max_length=50)),
                ('final_turbidity', models.CharField(default='', max_length=50)),
                ('cal_final_EC', models.CharField(default='', max_length=50)),
                ('delta_EC', models.CharField(default='', max_length=50)),
                ('stirring_speed_coagulation_phase', models.CharField(default='', max_length=50)),
                ('duration_coagulation_phase', models.CharField(default='', max_length=50)),
                ('stirring_speed_flocculation_phase', models.CharField(default='', max_length=50)),
                ('duration_flocculation_phase', models.CharField(default='', max_length=50)),
                ('duration_sedimentation_phase', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='testtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=70)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Date', models.DateField(default='')),
            ],
        ),
    ]
