# Generated by Django 4.1.3 on 2024-12-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_connection', '0002_bsf_data_alter_flocculation_data_cal_final_ec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aaa_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.FloatField(default='')),
                ('t', models.FloatField(default='')),
                ('q', models.FloatField(default='')),
            ],
        ),
    ]
