# Generated by Django 4.1.3 on 2024-12-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='predictAAAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.FloatField(default='5')),
                ('contact_time', models.FloatField(default='10')),
                ('concentration_chloride', models.FloatField(default='0')),
                ('concentration_sulfate', models.FloatField(default='0')),
                ('concentration_bicarbonate', models.FloatField(default='0')),
                ('concentration_hydrogen_phosphate', models.FloatField(default='0')),
                ('concentration_arsenic', models.FloatField(default='0')),
            ],
        ),
    ]
