from django.db import models

class predictBsfData(models.Model):
    print_assessment = models.BooleanField(blank=False, default=False)
    load_pipe = models.BooleanField(blank=False, default=False)
    diameter = models.IntegerField(blank=False, default="30")
    material_height = models.FloatField(blank=False, default="10")
    mean_grain_diameter = models.FloatField(blank=False, default="0.3")
    mean_flow = models.FloatField(blank=False, default="10")
    mean_pause = models.IntegerField(blank=False, default="24")
    time_schmutzdecke = models.IntegerField(blank=False, default="14")
    initial_turbidity = models.IntegerField(blank=False, default="50")

class optimizeBsfData(models.Model):
    print_assessment = models.BooleanField(blank=False, default=False)
    load_pipe = models.BooleanField(blank=False, default=False)
    diameter_min = models.IntegerField(blank=False, default="30")
    diameter_max = models.IntegerField(blank=False, default="30")
    material_height_min = models.FloatField(blank=False, default="10")
    material_height_max = models.FloatField(blank=False, default="10")
    mean_grain_diameter_min = models.FloatField(blank=False, default="0.3")
    mean_grain_diameter_max = models.FloatField(blank=False, default="0.3")
    mean_flow_min = models.FloatField(blank=False, default="10")
    mean_flow_max = models.FloatField(blank=False, default="10")
    mean_pause_min = models.IntegerField(blank=False, default="24")
    mean_pause_max = models.IntegerField(blank=False, default="24")
    time_schmutzdecke_min = models.IntegerField(blank=False, default="14")
    time_schmutzdecke_max = models.IntegerField(blank=False, default="14")
    initial_turbidity_min = models.IntegerField(blank=False, default="50")
    initial_turbidity_max = models.IntegerField(blank=False, default="50")