# Generated by Django 4.1.3 on 2022-11-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingdbcon', '0002_rename_testuserdbcon_testdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testdb',
            new_name='testtable',
        ),
    ]
