# Generated by Django 4.1.3 on 2023-03-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='optimizeBsfData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_assessment', models.BooleanField(default=False)),
                ('load_pipe', models.BooleanField(default=False)),
                ('diameter_min', models.IntegerField(default='30')),
                ('diameter_max', models.IntegerField(default='30')),
                ('material_height_min', models.FloatField(default='10')),
                ('material_height_max', models.FloatField(default='10')),
                ('mean_grain_diameter_min', models.FloatField(default='0.3')),
                ('mean_grain_diameter_max', models.FloatField(default='0.3')),
                ('mean_flow_min', models.FloatField(default='10')),
                ('mean_flow_max', models.FloatField(default='10')),
                ('mean_pause_min', models.IntegerField(default='24')),
                ('mean_pause_max', models.IntegerField(default='24')),
                ('time_schmutzdecke_min', models.IntegerField(default='14')),
                ('time_schmutzdecke_max', models.IntegerField(default='14')),
                ('initial_turbidity_min', models.IntegerField(default='50')),
                ('initial_turbidity_max', models.IntegerField(default='50')),
            ],
        ),
        migrations.CreateModel(
            name='predictBsfData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_assessment', models.BooleanField(default=False)),
                ('load_pipe', models.BooleanField(default=False)),
                ('diameter', models.IntegerField(default='30')),
                ('material_height', models.FloatField(default='10')),
                ('mean_grain_diameter', models.FloatField(default='0.3')),
                ('mean_flow', models.FloatField(default='10')),
                ('mean_pause', models.IntegerField(default='24')),
                ('time_schmutzdecke', models.IntegerField(default='14')),
                ('initial_turbidity', models.IntegerField(default='50')),
            ],
        ),
    ]
